### ISSUE TITLE
Build & installation issues

### ISSUE THREAD

**Issue by vranki** [jemc/qml-sockets#1]
Hello, thanks for very useful looking plugin. I was planning to write practically the same thing, but now there's no need.

But I have some issues building it:

qmake warns:

`WARNING: DESTDIR: Cannot access directory '/usr/lib/x86_64-linux-gnu/qt5/qml/org/jemc/qml/Sockets'`

..and not surprisingly make fails:

`mkdir: cannot create directory ‘/usr/lib/x86_64-linux-gnu/qt5/qml/org/jemc’: Permission denied`

Build should never be run as root, so I think the project file is not properly set up. Typically build compiles binaries in the project directory and make install (which is run as (fake)root) installs them. This also allows packaging. I might add debian packaging for this plugin later if needed.

**Comment by jemc** [comment]
@vranki - Thanks for your interest.  If you want to patch the build system, feel free to submit a pull request and I'll accept anything reasonable in this direction.

Otherwise I'll try to take a look at this tonight.

**Comment by jemc** [comment]
@vranki - Also, if you have any examples of QML plugins with good build systems, feel free to pass a link along to me here.

At the time I wrote this plugin, I think I had trouble finding good examples to mimic in the build system.

**Comment by vranki** [comment]
I have made this plugin:

https://github.com/vranki/qmljoystickplugin

 I don't know if it's good build system but works. Contains also debian packaging.

**Comment by jemc** [comment]
@vranki - Thanks, I'm pretty sure I was able to track down and resolve the issue.  Feel free to reopen if you still have build system trouble.
