### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by think-free** [jemc/qml-sockets#2]
Hi, I can't build for android. Tried from windows and linux ...

```
user@alderaan /tmp/qml-sockets/build $ mkdir android
user@alderaan /tmp/qml-sockets/build $ cd android/
user@alderaan /tmp/qml-sockets/build/android $ /opt/Qt/Qt5.5.0/5.5/android_armv7/bin/qmake /tmp/qml-sockets/qml-sockets.pro -r -spec android-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug
user@alderaan /tmp/qml-sockets/build/android $ make
make: *** No rule to make target '..//.moc/moc_qml-sockets.cpp', needed by '..//.obj/moc_qml-sockets.o'.  Stop.
```

I've tried with different path (build/android here) without success

From QtCreator windows : 

```
:-1: error: No rule to make target '..\..\qml-sockets-master\build\\.moc\moc_qml-sockets.cpp', needed by '..\..\qml-sockets-master\build\\.obj\moc_qml-sockets.obj'.  Stop.
:-1: error: No rule to make target '..\..\qml-sockets-master\build\\.moc\moc_qml-sockets.cpp', needed by '..\..\qml-sockets-master\build\\.obj\moc_qml-sockets.obj'.  Stop.
```

**Comment by jemc** [comment]
@think-free Thanks for reporting.

This build system for android was relying on an environment variable being set at `make` time - however, now `qmake` provides the variable I need at the time of `make` time, so I've changed it to use that.

Note also that you don't need to make your own subdirectory for building android by hand - the build system will automatically build into a subdir of `build` by android architecture (which is the part that is now fixed).
